---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "approval"
    labels: 
      app: "approval"
  spec: 
    selector: 
      matchLabels: 
        app: "approval"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "approval"
      spec: 
        containers: 
          - 
            name: "approval"
            image: "approval"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "approval"
    labels: 
      app: "approval"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "approval"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "reservation"
    labels: 
      app: "reservation"
  spec: 
    selector: 
      matchLabels: 
        app: "reservation"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "reservation"
      spec: 
        containers: 
          - 
            name: "reservation"
            image: "reservation"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "reservation"
    labels: 
      app: "reservation"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "reservation"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "point"
    labels: 
      app: "point"
  spec: 
    selector: 
      matchLabels: 
        app: "point"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "point"
      spec: 
        containers: 
          - 
            name: "point"
            image: "point"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "point"
    labels: 
      app: "point"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "point"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "bikemgmt"
    labels: 
      app: "bikemgmt"
  spec: 
    selector: 
      matchLabels: 
        app: "bikemgmt"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "bikemgmt"
      spec: 
        containers: 
          - 
            name: "bikemgmt"
            image: "bikemgmt"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "bikemgmt"
    labels: 
      app: "bikemgmt"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "bikemgmt"
