apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikeMgmt
  labels:
    app: bikeMgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bikeMgmt
  template:
    metadata:
      labels:
        app: bikeMgmt
    spec:
      containers:
        - name: bikeMgmt
          image: username/bikeMgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
